name: SSH VPS

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH
      run: |
        sudo apt update
        sudo apt install -y openssh-server
        sudo service ssh start
        echo "root:123456" | sudo chpasswd
        sudo sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo service ssh restart
        echo "Server Started"
        curl --silent --show-error ngrok-script.sh | bash
