name: SSH VPS via Ngrok

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup SSH Server with Ngrok
      run: |
        sudo apt update
        sudo apt install -y openssh-server wget unzip
        sudo systemctl enable ssh
        sudo systemctl start ssh
        echo "root:123456" | sudo chpasswd
        sudo sed -i 's/#Port 22/Port 22/' /etc/ssh/sshd_config
        sudo sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        sudo sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
        sudo systemctl restart ssh
        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        ./ngrok authtoken 2xBUu8LALUJXGLCVEIRuzC6ruNc_4q7YRnj4udGkw4LAS2Lir
        ./ngrok tcp 22 &
        sleep 5
        curl -s http://127.0.0.1:4040/api/tunnels

    - name: Keep Workflow Alive
      run: sleep 36000
